unstable_features = true
newline_style = "Unix"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true
normalize_comments = true
normalize_doc_attributes = true
format_code_in_doc_comments = true
use_field_init_shorthand = true
use_small_heuristics = "Max"
comment_width = 100
doc_comment_code_block_width = 100
wrap_comments = true
binop_separator = "Back"
trailing_comma = "Vertical"
trailing_semicolon = false
